import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import type { ReactNode } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Mini Dashboard',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body
        cz-shortcut-listen='true'
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='flex h-screen'>
          <Sidebar />
          <main className='flex-1 bg-gray-50 overflow-y-auto p-6'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
